default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # autoflake should run before isort, so isort can clean up after autoflake removes
  # unused imports
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          [
            --in-place,
            --remove-all-unused-imports,
            --ignore-init-module-imports,
          ]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--profile, black]

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black

  # Notes:
  # - We put flake8 last since previous hooks can auto-fix issues
  #   that flake8 would otherwise complain about.
  # - flake8 doesn't block commits from passing. `--exit-zero` means it won't cause
  #   pre-commit to fail, and `verbose: true` causes its output to always be
  #   emitted.
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [--exit-zero]
        verbose:
          true
          # additional_dependencies: [flake8-bugbear==21.11.29]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        types_or: [css, javascript, json, markdown, yaml]
