[tool.black]
line-length = 100
target-version = ['py311']
include = '\.pyi?$'

[tool.isort]
profile = "black"

# config file docs: https://mypy.readthedocs.io/en/stable/config_file.html
# type annotations notes: https://github.com/OpenLabsUSA/brr/wiki/type-annotations-stuff
[tool.mypy]
files = '.'
python_version = '3.11'
namespace_packages = true
show_column_numbers = true
show_error_codes = true
ignore_missing_imports = false

warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true

strict_equality = true
check_untyped_defs = true
## more strictness for later...
# disallow_untyped_defs = true
# disallow_untyped_decorators = true
# disallow_incomplete_defs = true
# warn_return_any = true
# implicit_reexport = false
# local_partial_types = true
